version: "3.3"

services:
  employeeservice-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'employeeservice_db'
      # Password for root access
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./employeeservice_db.sql:/docker-entrypoint-initdb.d/0_init.sql
